version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: always