name: CD Pipeline

on:
  push:
    branches:
      - prod   # Only deploy from prod branch

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production  # ← Manual approval required
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve