name: CD Pipeline

on:
  push:
    branches:
      - prod

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: infra/terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: infra/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="docker_image_tag=${{ github.sha }}"
        working-directory: infra/terraform
